In [2]:
# pip install numpy


In [3]:
import numpy as np

In [4]:
my_list=([1,2,3],[4,5,6])
arr=np.array(my_list)

In [5]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.shape

(2, 3)

In [8]:
# multi dim array
my_lt1=[1,5,3,4]
my_lt2=[3,9,2,2]
my_lt3=[7,4,0,5]
ar=np.array([my_lt1,my_lt2,my_lt3])

In [9]:
ar

array([[1, 5, 3, 4],
       [3, 9, 2, 2],
       [7, 4, 0, 5]])

In [10]:
ar.shape

(3, 4)

In [11]:
ar.reshape(12,1)

array([[1],
       [5],
       [3],
       [4],
       [3],
       [9],
       [2],
       [2],
       [7],
       [4],
       [0],
       [5]])

In [12]:
ar

array([[1, 5, 3, 4],
       [3, 9, 2, 2],
       [7, 4, 0, 5]])

In [13]:
# indexing
ar[1:,2:]

array([[2, 2],
       [0, 5]])

In [14]:
ar[0:2,2:]

array([[3, 4],
       [2, 2]])

In [15]:
ar=np.arange(0,9)  
# press shift+tab- on arange 

In [16]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [17]:
ar=np.arange(0,9,2)

In [18]:
ar

array([0, 2, 4, 6, 8])

In [19]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [20]:
ar[2:]=50

In [21]:
ar

array([ 0,  2, 50, 50, 50])

In [22]:
ar1=ar

In [23]:
# print(ar1)
ar1[2:]=50
print(ar1)

[ 0  2 50 50 50]


In [24]:
ar

array([ 0,  2, 50, 50, 50])

In [25]:
ar1=ar.copy()

In [26]:
print(ar)
ar1[2:]=60
print(ar1)

[ 0  2 50 50 50]
[ 0  2 60 60 60]


In [27]:
ar

array([ 0,  2, 50, 50, 50])

In [28]:
np.ones(2)

array([1., 1.])

In [30]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [33]:
np.ones((2,2),dtype=float)

array([[1., 1.],
       [1., 1.]])

In [39]:
# random distribution
np.random.rand(3,3)

array([[0.97442876, 0.54329858, 0.25721097],
       [0.7588759 , 0.32704098, 0.76486076],
       [0.25374997, 0.24498723, 0.6056426 ]])

In [40]:
np.random.randn(3,3)

array([[ 1.79651245,  1.76674268, -0.27720515],
       [-0.2453913 ,  0.4132722 ,  1.86449501],
       [ 1.08829605,  1.70742195, -0.50960989]])